In [1]:
# numpy.rollaxis 函数向后滚动特定的轴到一个特定位置

# numpy.rollaxis(arr, axis, start)
#     arr：数组
#     axis：要向后滚动的轴，其它轴的相对位置不会改变
#     start：默认为零，表示完整的滚动。会滚动到特定位置。


import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
# [[[0 1]       0(0,0,0)   1(0,0,1) 
#   [2 3]]      2(0,1,0)   3(0,1,1)

#  [[4 5]      4(1,0,0)    5(1,0,1)
#   [6 7]]]    6(1,1,0)    7(1,1,1)

# print ('获取数组中一个值：')
# print(np.where(a==6))   
# print(a[1,1,0])  # 为 6
# print ('\n')
 
 
print ('调用 rollaxis 函数：')  
b = np.rollaxis(a,2,0)  # 将数组a的轴 2 滚动到轴 0（宽度到深度）
print (b)

# [[[0 1]       0(0,0,0)--->(000)0   1(0,0,1)--->(010)2
#   [2 3]]      2(0,1,0)--->(100)4   3(0,1,1)--->(110)6

#  [[4 5]      4(1,0,0)--->(001)1    5(1,0,1)--->(011)3
#   [6 7]]]    6(1,1,0)--->(101)5    7(1,1,1)--->(111)7
# 即所得为：
# [[[0  2]
#   [4  6]]

#  [[1  3]
#   [5  7]]]

# 查看元素 a[1,1,0]，即 6 的坐标，变成 [0, 1, 1]
# 最后一个 0 移动到最前面
# print(np.where(b==6))   
# print ('\n')
 
# 将轴 2 滚动到轴 1：（宽度到高度）
 
print ('调用 rollaxis 函数：')
c = np.rollaxis(a,2,1)
print (c)
# [[[0 1]       0(0,0,0)--->(000)0   1(0,0,1)--->(010)2
#   [2 3]]      2(0,1,0)--->(001)1   3(0,1,1)--->(011)3

#  [[4 5]      4(1,0,0)--->(100)4   5(1,0,1)--->(110)6
#   [6 7]]]    6(1,1,0)--->(101)5   7(1,1,1)--->(111)7
# # 查看元素 a[1,1,0]，即 6 的坐标，变成 [1, 0, 1]
# # 最后的 0 和 它前面的 1 对换位置
# print(np.where(c==6))   
# print ('\n')


原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
获取数组中一个值：
(array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))
6


调用 rollaxis 函数：
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
(array([0], dtype=int64), array([1], dtype=int64), array([1], dtype=int64))


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))




In [2]:
# 连接数组

# numpy.concatenate

a = np.array([[1,2],[3,4]])
print ('第一个数组：')
print (a)
print ('\n')

b = np.array([[5,6],[7,8]])
print ('第二个数组：')
print (b)
print ('\n')
# 两个数组的维度相同
 
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b)))
print ('\n')
 
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


In [3]:
# numpy.stack 函数用于沿新轴连接数组序列

a = np.array([[1,2],[3,4]])
print ('第一个数组：')
print (a)
print ('\n')

b = np.array([[5,6],[7,8]])
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),0))
print ('\n')
 
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [6]:
a = np.array([[1,2],[3,4]])
print ('第一个数组：')
print (a)
# [[1,2]
#  [3,4]]
print ('\n')

b = np.array([[5,6],[7,8]])
print ('第二个数组：')
print (b)
# [[5,6]
#  [7,8]]
print ('\n')
 
print ('水平堆叠：')
c = np.hstack((a,b))   # stack((a,b),0)    stack((a,b),1)
print (c)
print ('\n')


print ('垂直堆叠：')
d = np.vstack((a,b))   # stack((a,b),0)    stack((a,b),1)
print (d)
print ('\n')

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


水平堆叠：
[[1 2 5 6]
 [3 4 7 8]]


垂直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




In [7]:
# 分割数组

a = np.arange(9)
print ('第一个数组：')
print (a)  #[0 1 2 3 4 5 6 7 8]
print ('\n')
 
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [10]:
# numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。

a = np.arange(16).reshape(4,4)
print ('第一个数组：')
print (a)
# [[ 0  1  2  3]  
#  [ 4  5  6  7]   
#  [ 8  9 10 11]   
#  [12 13 14 15]]  
print ('\n')
 
print ('竖直分割：')
b = np.vsplit(a,2)
print (b)


print ('水平分割：')
c = np.hsplit(a,2)
print (c)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
水平分割：
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
