In [1]:
import numpy as np 

# numpy.reshape
a = np.arange(8)
print ('原始数组：')
print (a)  # [0 1 2 3 4 5 6 7]
print ('\n')
 
b = a.reshape(4,2)
print ('修改后的数组：')
print (b)

原始数组：
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [3]:
# numpy.ndarray.flat    # flat 平铺 平展

a = np.arange(9).reshape(3,3)  # 3行3列
# print ('原始数组：')
# for row in a:   # 这个循环了几次？ 3次
#     print (row)

# print(list(a.flat))   # [0, 1, 2, 3, 4, 5, 6, 7, 8]
 
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')  #[0 1 2 3 4 5 6 6 7 8]
for element in a.flat:   # 循环9次
    print (element)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [4]:
# numpy.ndarray.flatten

a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
print ('\n')
# 默认按行
 
print ('展开的数组：')
# print (a.flatten())
print (a.flatten(order = 'C'))   # 等价上述行代码 展开顺序 先行后列
# [0 1 2 3 4 5 6 7]
print ('\n')
 
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'F')) # 等价上述行代码 展开顺序 先列后行
# [0 4 1 5 2 6 3 7]

原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组：
[0 1 2 3 4 5 6 7]


以 F 风格顺序展开的数组：
[0 4 1 5 2 6 3 7]


In [15]:
# numpy.ndarray.ravel  都是平铺数据，支持修改数据，并且影响原数组
# 展平的数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），
# 修改会影响原始数组
# numpy.ndarray.flatten  

a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('调用 ravel 函数之后：')
nd_ravel = a.ravel()
nd_ravel[0] = 100
print (nd_ravel)   # [100 1 2 3 4 5 6 7]
print(a)
print ('\n')
 
# print ('以 F 风格顺序调用 ravel 函数之后：')
# print(a.ravel(order = 'F'))   #  [0 4 1 5 2 6 3 7]




原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 ravel 函数之后：
[100   1   2   3   4   5   6   7]
[[100   1   2   3]
 [  4   5   6   7]]


