In [2]:
import numpy as np 
 
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],[0,1,0]]  
# 这种索引方式，是如何选取数据的：
# y = x[[0,1,2],[0,1,0]]   x[行[0,1,2]，列[0,1,0]]
# 进行行列 组合： (0,0)  (1,1)  (2,0)
print(y)


[1 4 5]


In [4]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
#    0   1
# 0[[1  2]
# 1[3  4]
# 2[5  6]]
y = x[[0,2],[0,1]] 
# x[[0,2],[0,1]] 意思 x[行[0,2],列[0,1]]
# 进行行列 组合定位数据：  坐标数据：(0,0) (2,1)
# (0,0)==> 1   （2，1）==>6
# 所以该高级索引 运行结果是  [1,6]
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 6]


In [5]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print('我们的数组是：' )
print(x)
print('\n')
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]  
# x[rows,cols] ==> x[行：[[0,0],[3,3]],列：[0,2],[0,2]]
# 进行行列组合：行（A,B）   列（x,y）
# 进行行列组合：   Ax   Ay
#                  Bx   By
# x[[0,0]，[0,2]]      x[[0,0]，[0,2]]
# x[[3,3]，[0,2]]      x[[3,3]，[0,2]]
# --------再次进行行列组合--------------------------------------
# (0,0)(0,2)==>0 2     (0,0)(0,2)==>0 2
# (3,0)(3,2)==>9 11     (3,0)(3,2)==>9 11

#    [[0 2]  [0 2]
#    [9 11] [9 11]]
# 该运行方式  求数组（矩阵的 左起斜对角线  ）
# [[ 0  2]
#  [ 9 11]]
print('这个数组的四个角元素是：')
print(y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


In [6]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print('我们的数组是：' )
print(x)
print('\n')
rows = np.array([[0,3],[3,1]]) 
cols = np.array([[0,1],[0,2]]) 
y = x[rows,cols]  
print('这个数组的四个角元素是：')
print(y)
# 左上的数据坐标 :  
# [0,3] [0,1] ===> 进一步行列组合：（0，0）==>0（3，1）==>10
# 右下的数据坐标 :  
# [3,1] [0,2] ===> 进一步行列组合：（3，0）==>9（1，2）==>5
# [0 10]
# [9 5]

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0 10]
 [ 9  5]]


In [7]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [8]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


In [9]:
a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [12]:
a = np.array([1,  2+6j,  5,  3.5+5j])  
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [13]:
x=np.arange(32).reshape((8,4))
# print(x)
print (x[[4,2,1,7]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [15]:
x=np.arange(32).reshape((8,4))
print(x[np.ix_([1,5,7,2],[0,3,1,2])])
print()
print(x[[1,5,7,2],[0,3,1,2]])  #行列组合 1,0  5,3  7,1  2,2
                               #          4    23   29   10

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

[ 4 23 29 10]
